version: "3"

services:
  server:
    container_name: html
    image: nginx:1.20.1
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - db
    # Deny all except localhost
    networks:
      default:
        external:
          name: my_network
    # End of deny all

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: M@el3692
    ports:
      - "8080:80"
    depends_on:
      - db
    # Deny all except localhost
    networks:
      default:
        external:
