version: "3"

services:
  server:
    container_name: html
    image: nginx:1.16.1
    volumes:
    - ./:/usr/share/nginx/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: 172.18.0.2 # Use the name of the Nginx container as the database host
      PMA_USER: root # coduiscript@138
      PMA_PASSWORD: M@el3692
    ports:
      - "8080:80" # Map the PHPMyAdmin port to port 8080 on the host machine
