
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: M@el3692
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: M@el3692
    volumes:
      - ./mysql:/var/lib/mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=Host(`db.eservease.com`)" 
      - "traefik.http.services.db.loadbalancer.server.port=3306"
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: M@el3692
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.eservease.com`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt"
    networks:
      - web

networks:
  web:
    external:
      name: nginx-proxy

