version: "3"

services:
  server:
    container_name: html
    image: nginx:1.20.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`eservease.com`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls=true"
      - "traefik.http.services.server.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik_proxy
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.eservease.com`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: M@el3692
    networks:
      - traefik_proxy
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: M@el3692
      MYSQL_DATABASE: testdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: M@el3692
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true

volumes:
  db_data:
