version: "3"

services:
  server:
    container_name: html
    image: nginx:1.16.1
    volumes:
    - ./:/usr/share/nginx/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: server
      PMA_USER: root
      PMA_PASSWORD: M@el3692
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: M@el3692
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
