version: "3"

services:
  server:
    container_name: html
    image: nginx:1.20.1
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - db

 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: M@el3692
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: M@el3692
      MYSQL_DATABASE: testdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: M@el3692
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
