version: "3"

services:
  server:
    container_name: html
    image: nginx:1.16.1
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - db

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: M@el3692
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: M@el3692
      MYSQL_DATABASE: testdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: M@el3692
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
