services:
  webserver:
    image: nginx:latest      
    container_name: webserver
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./Padyak/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  default:
    external:
      name: nginx-proxy
